---

galaxy_info:
  author: Liza Dayoub
  description: Elastic Stack
  company: elastic.co
  license: 'License (Apache)'
  min_ansible_version: '2.10'
  platforms:
    - name: Ubuntu
      versions:
        - "bionic"
        - "focal"
  galaxy_tags:
    - elasticsearch
    - kibana
    - logstash
    - beats

dependencies:
  - {role: common}
  - {role: heartbeat}
  - {role: elasticsearch}
  - {role: xpack_elasticsearch}
  - {role: logstash}
  - {role: xpack_elasticsearch}
  - {role: kibana}
  - {role: xpack_kibana}
