# ----------------------------------------------------------------------------
# kibana tasks
#
# Author: liza.dayoub@elastic.co
# ----------------------------------------------------------------------------
---

# Include task files in group use
- name: Include ait_role task files
  include: '{{ lookup("first_found", xpack_kibana_task_files) }} ait_args={{ item.args }}'
  with_items: '{{ xpack_kibana_roles[ait_role] }}'
  when: ait_role is defined and xpack_kibana_roles[ait_role] is defined

- name: Include ait_action task file
  include: '{{ lookup("first_found", xpack_kibana_task_files) }}'
  vars:
    item:
      action: '{{ ait_action }}'
      parent: ''
  when: ait_action is defined
